apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lafayette96-poi-map-app-dev
  annotations:
    argocd/app-name: lafayette96-poi-map-app-dev
    backstage.io/kubernetes-id: lafayette96-poi-map-app
    backstage.io/kubernetes-namespace: lafayette96
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh23-demo/lafayette96-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/dev-pipelines/ns/lafayette96/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/k8s/ns/lafayette96/deployments/lafayette96-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/#https://github.com/rhdh23-demo/lafayette96-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://lafayette96-poi-map-app-lafayette96.apps.rosa-pzz6v.9nln.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/lafayette96"
  system: workshop-system-lafayette96
  consumesApis:
    - gateway-api-lafayette96
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-lafayette96
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/lafayette96"
